const express = require('express');
const authRoutes = require('../modules/auth/auth.routes');
const userRoutes = require('../modules/users/user.routes');
const supplierRoutes = require('../modules/suppliers/supplier.routes');
const productRoutes = require('../modules/products/product.routes');
const customerRoutes = require('../modules/customers/customer.routes');
const stockReceiptRoutes = require('../modules/stock_receipts/stock_receipt.routes');
const salesRoutes = require('../modules/sales/sales.routes');
const returnsRoutes = require('../modules/returns/returns.routes');
const supplierPaymentRoutes = require('../modules/supplier_payments/supplier_payment.routes');
const customerPaymentRoutes = require('../modules/customer_payments/customer_payment.routes');
const expenseRoutes = require('../modules/expenses/expense.routes');
const customerOperationsRoutes = require('../modules/customer_operations/customer_operations.routes');
const supplierOperationsRoutes = require('../modules/supplier_operations/supplier_operations.routes');
const debtorsRoutes = require('../modules/debtors/debtors.routes');
const debtorOperationsRoutes = require('../modules/debtor_operations/debtor_operations.routes');
const overdueSalesRoutes = require('../modules/sales/overdue-sales.routes');
const salariesSimpleRoutes = require('../modules/salaries/salaries-simple.routes');
const accountsRoutes = require('../modules/accounts/accounts.routes');
const reportsRoutes = require('../modules/reports/reports.routes');
const conversionsRoutes = require('../modules/conversions/conversions.routes');
const exchangeRatesRoutes = require('../modules/exchange_rates/exchange_rates.routes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/products', productRoutes);
router.use('/customers', customerRoutes);
router.use('/stock-receipts', stockReceiptRoutes);
router.use('/sales', salesRoutes);
router.use('/returns', returnsRoutes);
router.use('/supplier-payments', supplierPaymentRoutes);
router.use('/customer-payments', customerPaymentRoutes);
router.use('/expenses', expenseRoutes);
router.use('/customer-operations', customerOperationsRoutes);
router.use('/supplier-operations', supplierOperationsRoutes);
router.use('/debtors', debtorsRoutes);
router.use('/debtor-operations', debtorOperationsRoutes);
router.use('/overdue-sales', overdueSalesRoutes);
router.use('/salaries', salariesSimpleRoutes);
router.use('/accounts', accountsRoutes);
router.use('/reports', reportsRoutes);
router.use('/conversions', conversionsRoutes);
router.use('/exchange-rates', exchangeRatesRoutes);

module.exports = router;
